#!/usr/bin/env bash
# Session state snapshot for the PreCompact hook (B-0025).
#
# Appends a timestamped block to the active initiative's Status.md
# capturing: branch, git HEAD, dirty files, last tier statuses.
# The post-compact model reads Status.md; this ensures it has a
# fresh snapshot even if the implementing agent didn't explicitly
# invoke the context-handoff skill before compaction fired.
#
# Usage: scripts/snapshot_session.sh [initiative-slug]
# If omitted, the script reads HANDOFF.md for an active-initiative
# pointer, else picks the most-recently-modified non-archive run
# folder under .agent/runs/.

set -euo pipefail

ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$ROOT"

if [[ $# -ge 1 ]]; then
  SLUG="$1"
  DIR=".agent/runs/${SLUG}"
else
  # Best-effort: grep HANDOFF.md or fall back to most recent.
  if [[ -f .agent/HANDOFF.md ]]; then
    SLUG=$(grep -oE '\.agent/runs/[a-zA-Z0-9_-]+' .agent/HANDOFF.md | head -1 | sed 's|.agent/runs/||')
  fi
  if [[ -z "${SLUG:-}" ]]; then
    SLUG=$(ls -1t .agent/runs/ 2>/dev/null \
           | grep -v -E '^(_archive|\.)' \
           | head -1 || true)
  fi
  if [[ -z "${SLUG:-}" ]]; then
    echo "snapshot_session: no active initiative found; nothing to snapshot" >&2
    exit 0
  fi
  DIR=".agent/runs/${SLUG}"
fi

if [[ ! -d "$DIR" ]]; then
  echo "snapshot_session: $DIR does not exist" >&2
  exit 0
fi

STATUS="${DIR}/Status.md"
if [[ ! -f "$STATUS" ]]; then
  echo "snapshot_session: $STATUS does not exist" >&2
  exit 0
fi

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "<not-a-git-repo>")
HEAD_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "<no-head>")
DIRTY_SUMMARY=$(git status --porcelain=v1 2>/dev/null | head -15 || echo "<no-status>")
DIRTY_COUNT=$(git status --porcelain=v1 2>/dev/null | wc -l | tr -d ' ' || echo 0)

{
  echo ""
  echo "## PreCompact snapshot — ${TS}"
  echo ""
  echo "- branch: \`${BRANCH}\`"
  echo "- HEAD: \`${HEAD_SHA}\`"
  echo "- dirty files: ${DIRTY_COUNT}"
  if [[ -n "$DIRTY_SUMMARY" && "$DIRTY_SUMMARY" != "<no-status>" ]]; then
    echo ""
    echo "\`\`\`"
    echo "$DIRTY_SUMMARY"
    echo "\`\`\`"
  fi
  echo ""
  echo "_Auto-generated by scripts/snapshot_session.sh (B-0025 PreCompact hook)._"
} >> "$STATUS"

echo "snapshot_session: appended block to ${STATUS}" >&2
